;;;; 9ML-alsys-lib.import.scm - GENERATED BY CHICKEN 4.9.0.1 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         datatype
         matchable
         static-modules
         miniML
         miniMLsyntax
         miniMLvalue
         miniMLeval
         object-graph
         algebraic-system
         9ML-parse
         9ML-eval
         9ML-plot
         9ML-alsys-mlton
         (only files pathname-file)
         (only utils system*)
         (only extras fprintf)
         (only posix process-fork)
         (only data-structures string-intersperse ->string alist-ref)
         (only srfi-1 lset-intersection lset-difference)))
(##sys#register-compiled-module
  '9ML-alsys-lib
  (list)
  '((alsys-verbose . 9ML-alsys-lib#alsys-verbose)
    (alsys-simulation-platform . 9ML-alsys-lib#alsys-simulation-platform)
    (make-alsys-cgen-hook . 9ML-alsys-lib#make-alsys-cgen-hook))
  (list)
  (list))

;; END OF FILE
