;;;; 9ML-ivp-mlton.import.scm - GENERATED BY CHICKEN 4.9.0.1 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         (only files make-pathname pathname-directory pathname-file)
         (only data-structures conc alist-ref intersperse)
         (only srfi-13 string-concatenate)
         (only srfi-1 delete-duplicates)
         make
         datatype
         signal-diagram
         9ML-eval
         setup-api))
(##sys#register-compiled-module
  '9ML-ivp-mlton
  (list)
  '((ivp-mlton . 9ML-ivp-mlton#ivp-mlton)
    (ivp-mlton-codegen . 9ML-ivp-mlton#ivp-mlton-codegen)
    (mlton-initial . 9ML-ivp-mlton#mlton-initial)
    (mlton-state-update . 9ML-ivp-mlton#mlton-state-update)
    (mlton-value . 9ML-ivp-mlton#mlton-value))
  (list)
  (list))

;; END OF FILE
