;;;; 9ML-ivp-octave-mlton.import.scm - GENERATED BY CHICKEN 4.9.0.1 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         (only files
               make-pathname
               pathname-directory
               pathname-file
               absolute-pathname?)
         (only data-structures conc alist-ref intersperse)
         (only posix current-directory)
         (only srfi-1 filter list-index)
         (only srfi-13 string-concatenate)
         make
         datatype
         signal-diagram
         9ML-eval
         9ML-ivp-mlton
         setup-api))
(##sys#register-compiled-module
  '9ML-ivp-octave-mlton
  (list)
  '((ivp-octave-mlton . 9ML-ivp-octave-mlton#ivp-octave-mlton)
    (ivp-octave-mlton-codegen . 9ML-ivp-octave-mlton#ivp-octave-mlton-codegen))
  (list)
  (list))

;; END OF FILE
