;;;; 9ML-toolkit.import.scm - GENERATED BY CHICKEN 4.9.0.1 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         (only srfi-1 list-tabulate)
         (only data-structures ->string)
         static-modules
         miniML
         miniMLsyntax
         miniMLvalue
         miniMLeval))
(##sys#register-compiled-module
  '9ML-toolkit
  (list)
  '((datacon . 9ML-toolkit#datacon)
    (Real:module-initialize . 9ML-toolkit#Real:module-initialize)
    (Random:module-initialize . 9ML-toolkit#Random:module-initialize)
    (Signal:module-initialize . 9ML-toolkit#Signal:module-initialize)
    (Diagram:module-initialize . 9ML-toolkit#Diagram:module-initialize)
    (IVP:module-initialize . 9ML-toolkit#IVP:module-initialize))
  (list)
  (list))

;; END OF FILE
