;;;; 9ML-ivp-lib.import.scm - GENERATED BY CHICKEN 4.9.0.1 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         datatype
         matchable
         static-modules
         miniML
         miniMLsyntax
         miniMLvalue
         miniMLeval
         object-graph
         signal-diagram
         9ML-parse
         9ML-eval
         9ML-plot
         9ML-ivp-octave
         9ML-ivp-chicken
         9ML-ivp-mlton
         9ML-ivp-octave-mlton
         (only files pathname-file)
         (only utils system*)
         (only extras fprintf pp)
         (only posix process-fork)
         (only data-structures string-intersperse ->string alist-ref)
         (only srfi-1 lset-intersection lset-difference filter)))
(##sys#register-compiled-module
  '9ML-ivp-lib
  (list)
  '((ivp-verbose . 9ML-ivp-lib#ivp-verbose)
    (ivp-simulation-platform . 9ML-ivp-lib#ivp-simulation-platform)
    (ivp-simulation-method . 9ML-ivp-lib#ivp-simulation-method)
    (make-ivp-cgen-hook . 9ML-ivp-lib#make-ivp-cgen-hook)
    (make-ivp-data-hook . 9ML-ivp-lib#make-ivp-data-hook)
    (make-ivp-plot-hook . 9ML-ivp-lib#make-ivp-plot-hook))
  (list)
  (list))

;; END OF FILE
