;;;; 9ML-alsys-mlton.import.scm - GENERATED BY CHICKEN 4.9.0.1 -*- Scheme -*-

(eval '(import
         scheme
         chicken
         (only files make-pathname pathname-directory pathname-file)
         (only extras sprintf)
         (only data-structures conc alist-ref intersperse)
         (only srfi-13 string-concatenate)
         (only srfi-1 delete-duplicates)
         make
         datatype
         algebraic-system
         9ML-eval
         setup-api))
(##sys#register-compiled-module
  '9ML-alsys-mlton
  (list)
  '((alsys-mlton-codegen . 9ML-alsys-mlton#alsys-mlton-codegen)
    (mlton-initial . 9ML-alsys-mlton#mlton-initial)
    (mlton-state-update . 9ML-alsys-mlton#mlton-state-update)
    (mlton-value . 9ML-alsys-mlton#mlton-value))
  (list)
  (list))

;; END OF FILE
