all: Sim_{{group.name}}


{{exec_path}}: {% for path in src_paths %}{{path}} {% endfor %}

	mlton {% if ExnHistory %} -const 'Exn.keepHistory true' {% endif %} -default-ann 'allowFFI true' -cc-opt "-O3" -mlb-path-var "SALT_HOME {{salt_home}}" -mlb-path-var "SALT_LIB {{sml_lib_home}}" -mlb-path-map "{{sml_lib_home}}/mlb-path-map" -mlb-path-var "TENSOR_LIB {{nineml_lib_home}}" -mlb-path-var "NINEML_LIB {{nineml_lib_home}}" -output {{exec_path}}  $< {{sml_lib_home}}/randmtzig/randmtziglib.c {% if UseCSolver %}{% for pop in dict (group.populations) %}{{build_dir}}/{{pop.value.prototype.name}}.c {% endfor %} {% for f in CSolverFiles %}{{f}} {% endfor %}{% endif %} 
